#pragma once

#define ZDRECORDING_VERSION_MAJOR  1
#define ZDRECORDING_VERSION_MINOR  0
#define ZDRECORDING_VERSION_PATCH  0

#define VERSION_STR(x) VERSION_FMT(x)
#define VERSION_FMT(x) #x

#define ZDRECORDING_VERSION        ZDRECORDING_VERSION_MAJOR.ZDRECORDING_VERSION_MINOR.ZDRECORDING_VERSION_PATCH
#define ZDRECORDING_VERSION_STR    VERSION_STR(ZDRECORDING_VERSION)

#define ZDRECORDING_FILE_VERSION          ZDRECORDING_VERSION.0
#define ZDRECORDING_FILE_VERSION_STR      VERSION_STR(ZDRECORDING_FILE_VERSION)
#define ZDRECORDING_PRODUCT_VERSION_STR   ZDRECORDING_FILE_VERSION_STR
